spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/graduation
    username: root
    password: 12344

server:
  port: 8082

mybatis:
  configuration:
    map-underscore-to-camel-case: true  # 驼峰命名
  mapper-locations: classpath:dao/*.xml # 配置mapper.xml的路径
  type-aliases-package: com.cuit.pojo   # 配置实体类包名

