server:
  port: 8087

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true  #是否与服务注册于发现组件结合，通过 serviceId 转发到具体的服务
          lower-case-service-id: true
      routes:
        - id: userservice
          uri: lb://user-service
          predicates:
            - Path=/user/**, /login, /register, /admin/**,/booking/**,/record/**
        - id: msgservice
          uri: lb://message-service
          predicates:
            - Path=/msguser/**, /msgadmin/**,/trip/**
        - id: complaintsservice
          uri: lb://complaints-service
          predicates:
            - Path=/complaints/**, /replies/**,/advice/**
        - id: commentsservice
          uri: lb://comments-service
          predicates:
            - Path=/comadmin/**, /comuser/**
        - id: annoservice
          uri: lb://announcement-service
          predicates:
            - Path=/anno/**
        - id: abnoservice
          uri: lb://abnormal-service
          predicates:
            - Path=/abno/**,/heal/**
      globalcors: # 全局跨域处理
        add-to-simple-url-handler-mapping: true # 解决options(对服务器的询问:询问是否允许跨域)请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:5173"
              - "http://localhost:5174"
              - "http://localhost:5175"
              - "http://localhost:5176"
              - "http://www.baidu.com"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowedCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域请求检测的有效期(秒)
