server:
  port: 8085

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/message
    username: root
    password: 12344
  application:
    name: message-service # user服务的服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos服务地址
#      discovery:
#        cluster-name: CD # 配置集群名称(分地区: 比如成都

mybatis:
  configuration:
    map-underscore-to-camel-case: true  # 驼峰命名
  mapper-locations: classpath:mapper/*.xml # 配置mapper.xml的路径
  type-aliases-package: cn.cuit.entity   # 配置实体类包名

#ribbon:
#  eager-load:
#    enabled: true # 开启饥饿加载
#    clients:      # 指定饥饿加载服务名称
#      - userservice

# 消费者 中设置负载均衡规则,这个配置会优先寻找与自己同集群的服务
# 比如这里需要对提供者进行请求:
#userservice:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则
